# Base image with web server
FROM nginx:latest

# Copy Flutter build files to the Nginx server's web directory
COPY build/web /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 8080 for the web server
EXPOSE 8080
